name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "newsnow"
database_name = "newsnow"  # 替换为你创建的数据库名称
database_id = "1452ab58-8934-427d-b423-b1839f520647"      # 替换为你创建的数据库 ID
